return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    -- Automatically install missing parsers when entering buffer
    auto_install = true,
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "dockerfile",
      "go",
      "gomod",
      "html",
      "javascript",
      "json",
      "latex",
      "lua",
      "make",
      "python",
      "regex",
      "toml",
      "typescript",
      "vim",
      "yaml",
      "rust",
      "jq",
    },
  },
}
